esphome:
  name: dolcificatore_serra_laser
  platform: ESP32
  board: esp-wrover-kit
  #  platform: ESP8266
  #board: nodemcuv2 
wifi:
  ssid: !secret SSID
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Led Strip 1 Fallback Hotspot"
    password: !secret wifi_password 

captive_portal:

# Enable logging
logger:

    # Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time
i2c:
       - sda: 21
         scl: 22
         id: bus_a
         frequency: 200khz
         scan: True
       - sda: 13
         scl: 16
         id: bus_b
         frequency: 200khz
         scan: True


sensor:
      - platform: wifi_signal
        name: "WiFi Signal Sensor"
        update_interval: 60s
      - platform: uptime
        name: "Uptime"
      - platform: vl53l0x
        name: "Livello Sale 1"
        update_interval: 500ms
        filters:
          - offset: -0.14
          - exponential_moving_average:
              alpha: 0.1
              send_every: 15
      - platform: vl53l0x
        name: "Livello sale 2"
        update_interval: 500ms
        filters:
          - offset: -0.14
          - exponential_moving_average:
              alpha: 0.1
              send_every: 15
       

switch:
  - platform: restart
    name: "ESP32 Restart"
# Enable Home Assistant API
api:
     password: !secret api_password

ota:
     safe_mode: True
     password: !secret ota_password

web_server:
  port: 80

