esphome:
  name: dolcificatore_serra
  platform: ESP8266
  board: nodemcuv2 
wifi:
  ssid: !secret SSID
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Led Strip 1 Fallback Hotspot"
    password: !secret wifi_password 

captive_portal:

# Enable logging
logger:

    # Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

sensor:
      - platform: wifi_signal
        name: "WiFi Signal Sensor"
        update_interval: 60s
      - platform: uptime
        name: "Uptime"
      - platform: ultrasonic
        trigger_pin: D7
        echo_pin: D6
        name: "Livello Sale 1"
        update_interval: 1.211s
        pulse_time: 50us
        #        timeout: 3m
        filters:
           - sliding_window_moving_average:
               window_size: 150
               send_every: 1
           - lambda: return (0.8-x)*(100/0.8);
        unit_of_measurement: "%"
      - platform: ultrasonic
        trigger_pin: D2
        echo_pin: D1
        name: "Livello Sale 2"
        update_interval: 1s
        pulse_time: 50us
        timeout: 3m
        filters: 
          - sliding_window_moving_average:
               window_size: 150
               send_every: 1
          - lambda: return (0.8-x)*(100/0.8);
        unit_of_measurement: "%"

switch:
  - platform: restart
    name: "ESP32 Restart"
# Enable Home Assistant API
api:
     password: !secret api_password

ota:
     safe_mode: True
     password: !secret ota_password

web_server:
  port: 80

