esphome:
  name: dolcificatore_serra
  platform: ESP8266
  board: nodemcuv2 
wifi:
  ssid: !secret SSID
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Led Strip 1 Fallback Hotspot"
    password: !secret wifi_password 

captive_portal:

# Enable logging
logger:

sensor:
      - platform: wifi_signal
        name: "WiFi Signal Sensor"
        update_interval: 60s
      - platform: uptime
        name: "Uptime"
      - platform: ultrasonic
        trigger_pin: D2
        echo_pin: D1
        name: "Livello Sale"
        update_interval: 1s
        pulse_time: 20us
        timeout: 3m
        filters:
          - sliding_window_moving_average:
              window_size: 10
              send_every: 10
              send_first_at: 10
      - platform: ultrasonic
        trigger_pin: D2
        echo_pin: D1
        name: "Livello Sale Percentuale"
        update_interval: 1s
        pulse_time: 20us
        timeout: 3m
        filters: #sostituire 0.42 con l'altezza reale del contenitore
          - lambda: return (0.42-x)*(100/0.42);
        unit_of_measurement: "%"

switch:
  - platform: restart
    name: "ESP32 Restart"
# Enable Home Assistant API
api:
     password: !secret api_password

ota:
     safe_mode: True
     password: !secret ota_password
